pipeline {
  agent none
  
  stages {
    stage('Build') {
      agent {
        docker {
          image 'python:2.7.16-slim'
          args '--user root'
        }
      }
      when {
        changeset '**/vote/**'
      }
      steps {
        dir('vote') {
          sh 'pip install -r requirements.txt'
        }
      }
    }
    stage('Test') {
      agent {
        docker {
          image 'python:2.7.16-slim'
          args '--user root'
        }
      }
      when {
        changeset '**/vote/**'
      }
      steps {
        dir('vote') {
          sh 'nosetests -v'
        }
      }
    }
    stage('docker-package') {
      agent any
      when {
        changeset '**/vote/**'
        branch 'master'
      }
      steps {
        echo 'packaging vote app with docker'
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
            def voteImage = docker.build("kaloraifi/vote:v${env.BUILD_ID}", "./vote")
            voteImage.push()
            voteImage.push("${env.BRANCH_NAME}")
          }
        }
      }
    }
  }

  post {
    always {
      echo 'python vote app pipeline completed..'
    }
  }
}